### ISSUE TITLE
Scalability Issues

### ISSUE THREAD

**Issue by satvik-27199** [bflashcp3f/schema-to-json#4]
Thank you for your amazing work and for making the code and data available to the public. I have reproduced the results with GPT-4 on the mltables dataset test.json. 
I wonder if your approach is scalable for large-scale datasets, as parsing the test alone took about half an hour?? Any suggestions?

**Comment by bflashcp3f** [comment]
Hi @satvik-27199,

Thanks for your interest and for confirming the reproducibility of our results. Here are a few adjustments you can make to speed up inference on large-scale datasets:

1. In my implementation, the default interval between two prompting requests ("sleep_time") is set to 5 seconds to avoid exceeding OpenAI's [rate limits](https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-one). Depending on your user tier, you may reduce this interval.
2. Instead of processing all tables sequentially, consider processing them in parallel. If you prefer not to modify the code, a simple alternative is to split your file into smaller segments and run the script multiple times, each with a different input file name.
3. If cost is not a concern, you can enhance efficiency by prompting at the cell level, which allows for parallel processing within a table.
4. To create customized smaller and faster models, consider implementing knowledge distillation as described in Section 4.6 of the paper.

Please don't hesitate to reach out if you have any more questions.
